name: Deploy on pages

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: deploy-pages
  cancel-in-progress: true

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: setup pages
        uses: actions/configure-pages@v5
      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: "../docs"
      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4
