name: reusable

on:
  workflow_dispatch:
    inputs:
      actor:
        description: "The person who will receive the greeting"
        required: true

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - name: Greetings message
        run: |
          echo "Well done: $ACTOR you've implemented reusable workflows successfully!"
        env:
          ACTOR: ${{ inputs.actor }}
